### ISSUE TITLE
Cannot Become a Scratcher, error agreeing to community guidelines

### ISSUE THREAD

**Issue by Donutask** [scratchfoundation/scratch-www#9086]
### Expected Behavior
The button "I Agree" at the end of the Become a Scratcher onboarding should promote the user to Scratcher status.

### Actual Behavior
![Screenshot 2024-12-29 at 10 32 17 AM](https://github.com/user-attachments/assets/d40f9779-e752-456c-ba9a-6ca5d42c3888)
There are multiple errors when clicking "I Agree"

Logs
common.bundle.js:2 
GET https://scratch.mit.edu/users/CharuzuBeru/promote-to-scratcher/ 404 (Not Found)
u @ common.bundle.js:2
l @ common.bundle.js:2
n @ common.bundle.js:2
e.exports @ common.bundle.js:2
onClick @ become-a-scratcher.bundle.js:2
s @ common.bundle.js:2
h @ common.bundle.js:2
(anonymous) @ common.bundle.js:2
_ @ common.bundle.js:2
st @ common.bundle.js:2
at @ common.bundle.js:2
lt @ common.bundle.js:2
pt @ common.bundle.js:2
H @ common.bundle.js:2
U @ common.bundle.js:2
Jt @ common.bundle.js:2
$t @ common.bundle.js:2
t.unstable_runWithPriority @ common.bundle.js:2
Zi @ common.bundle.js:2
I @ common.bundle.js:2
Qt @ common.bundle.js:2Understand this errorAI
common.bundle.js:2 Uncaught InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').
    at XMLHttpRequest.o (common.bundle.js:2:353920)
o @ common.bundle.js:2
load
u @ common.bundle.js:2
l @ common.bundle.js:2
n @ common.bundle.js:2
e.exports @ common.bundle.js:2
onClick @ become-a-scratcher.bundle.js:2
s @ common.bundle.js:2
h @ common.bundle.js:2
(anonymous) @ common.bundle.js:2
_ @ common.bundle.js:2
st @ common.bundle.js:2
at @ common.bundle.js:2
lt @ common.bundle.js:2
pt @ common.bundle.js:2
H @ common.bundle.js:2
U @ common.bundle.js:2
Jt @ common.bundle.js:2
$t @ common.bundle.js:2
t.unstable_runWithPriority @ common.bundle.js:2
Zi @ common.bundle.js:2
I @ common.bundle.js:2
Qt @ common.bundle.js:2Understand this errorAI
common.bundle.js:2 Uncaught InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').
    at r (common.bundle.js:2:353372)
    at o (common.bundle.js:2:353920)
r @ common.bundle.js:2
o @ common.bundle.js:2
setTimeout
c.onreadystatechange @ common.bundle.js:2
XMLHttpRequest.send
u @ common.bundle.js:2
l @ common.bundle.js:2
n @ common.bundle.js:2
e.exports @ common.bundle.js:2
onClick @ become-a-scratcher.bundle.js:2
s @ common.bundle.js:2
h @ common.bundle.js:2
(anonymous) @ common.bundle.js:2
_ @ common.bundle.js:2
st @ common.bundle.js:2
at @ common.bundle.js:2
lt @ common.bundle.js:2
pt @ common.bundle.js:2
H @ common.bundle.js:2
U @ common.bundle.js:2
Jt @ common.bundle.js:2
$t @ common.bundle.js:2
t.unstable_runWithPriority @ common.bundle.js:2
Zi @ common.bundle.js:2
I @ common.bundle.js:2
Qt @ common.bundle.js:2Understand this errorAI

### Steps to Reproduce
1. Create a Scratch account
2. Interact with website to meet the requirements to be able to become Scratcher (instead of New Scratcher)
3. Accept the invitation to become a Scratcher
4. Complete the onboarding process (Issue #9072 makes this difficult)
5. Click "I Agree" on end screen

### System Details
Chrome 131 on macOS (Sonoma)

**Comment by GoldenDuck13** [comment]
Seems to be fixed
